# Generated by Django 5.1.7 on 2025-03-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='id_equipment',
            field=models.ManyToManyField(related_name='rooms', to='equipment.equipment'),
        ),
    ]
