# Generated by Django 5.1.7 on 2025-04-03 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_room_id_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityReason',
            fields=[
                ('id_reason', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LocationAvailability',
            fields=[
                ('id_status_loc', models.AutoField(primary_key=True, serialize=False)),
                ('begin_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.availabilityreason')),
            ],
        ),
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id_status_room', models.AutoField(primary_key=True, serialize=False)),
                ('begin_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.availabilityreason')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.room')),
            ],
        ),
    ]
