# Generated by Django 5.1.7 on 2025-04-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_availabilityreason_locationavailability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationavailability',
            name='begin_datetime',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='locationavailability',
            name='end_datetime',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='roomavailability',
            name='begin_datetime',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='roomavailability',
            name='end_datetime',
            field=models.DateField(),
        ),
    ]
