# Generated by Django 5.1.7 on 2025-03-24 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id_booking', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('review', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('no_show', 'No Show'), ('confirmed', 'Confirmed'), ('cancelled_by_user', 'Cancelled by User'), ('cancelled_by_admin', 'Cancelled by Admin'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='location.room')),
                ('slot', models.ManyToManyField(to='location.timeslot')),
            ],
        ),
    ]
