# Generated by Django 5.1.7 on 2025-04-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='code',
            field=models.IntegerField(default=100000),
            preserve_default=False,
        ),
    ]
