# Generated by Django 5.1.7 on 2025-04-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='review',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
