# Generated by Django 5.1.7 on 2025-04-03 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_id',
            new_name='id_user',
        ),
    ]
