# Generated by Django 5.1.7 on 2025-04-15 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_location_alter_customuser_username'),
    ]

    operations = [
        
    ]
