# Generated by Django 5.1.7 on 2025-04-15 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_delete_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
